version: "3.9"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
  postgres:
    container_name: postgres
    image: postgres:12.3-alpine
    restart: always
    ports:
      - "5900:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
      APP_DB_USER: app
      APP_DB_PASS: pass
    volumes:
      - ./scripts/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh 