app:
  port: 7001
  host: 0.0.0.0

db:
  migrationsSourceURL: file://migrations
  hostname: scb-monitor.ru
  port: 5432
  username: scb_monitor
  password: fjdsj234mrktio4
  databaseName: scb_monitor

keycloak:
  base-path: https://kc.scb-monitor.ru
  realm: master
