app:
  port: 8080
  host: 0.0.0.0

db:
  migrationsSourceURL: file://migrations
  hostname: localhost
  port: 5433
  username: golang
  password: golang
  databaseName: golang

keycloak:
  base-path: https://kc.some-url.ru
  realm: master